import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-end items-center p-4 gap-4 h-16"></header>

        <main>
          {children}

          <div className="flex flex-col items-center justify-center min-h-[70vh] text-center">
            <h1 className="text-2xl font-semibold mb-4">
              Please sign in to access the app
            </h1>
          </div>
        </main>
      </body>
    </html>
  );
}
